version: '3.8'
services:
  db:
    image: postgres:15.4
    restart: always
    environment:
      - POSTGRES_USER=resumeuser
      - POSTGRES_PASSWORD=resumepass
      - POSTGRES_DB=resumedb
    ports:
      - '5432:5432'
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
